# .tbls.yml

# DSN (Database Source Name) to connect database
dsn: postgres://raif_partners:raif_partners@localhost:5432/raif_partners?sslmode=disable

# Path to generate document
# Default is `dbdoc`
docPath: doc/schema2

templates:
  dot:
    schema: 'output/dot/templates/schema.dot.tmpl'
    table: 'output/dot/templates/table.dot.tmpl'
  puml:
    schema: 'output/plantuml/templates/schema.puml.tmpl'
    table: 'output/plantuml/templates/table.puml.tmpl'
  md:
    index: 'output/md/templates/index.md.tmpl'
    table: 'output/md/templates/table.md.tmpl'
